// Sinhala transliteration table, indexed by (codepoint - 0x0D80)
// Each entry: [itrans, iso, ipa] — null = pass through original character
// IPA uses plain a as inherent vowel — consistently pronounced in Sinhala.
var sinhalaTable = (function () {
  const t = new Array(0x80).fill(null);
  t[0x01] = ['ⁿ', 'ṁ', 'n'];
  t[0x02] = ['ᵐ', 'ṃ', 'n'];
  t[0x03] = ['H', 'ḥ', 'h'];
  t[0x05] = ['a', 'a', 'a'];
  t[0x06] = ['A', 'ā', 'aː'];
  t[0x07] = ['ae', 'æ', 'æ'];
  t[0x08] = ['aae', 'ǣ', 'æː'];
  t[0x09] = ['i', 'i', 'i'];
  t[0x0a] = ['I', 'ī', 'iː'];
  t[0x0b] = ['u', 'u', 'u'];
  t[0x0c] = ['U', 'ū', 'uː'];
  t[0x0d] = ['ri', 'ṛ', 'ri'];
  t[0x0e] = ['ri', 'ṝ', 'riː'];
  t[0x0f] = ['li', 'ḷ', 'li'];
  t[0x10] = ['li', 'ḹ', 'liː'];
  t[0x11] = ['e', 'e', 'e'];
  t[0x12] = ['E', 'ē', 'eː'];
  t[0x13] = ['ai', 'ai', 'aj'];
  t[0x14] = ['o', 'o', 'o'];
  t[0x15] = ['O', 'ō', 'oː'];
  t[0x16] = ['au', 'au', 'aʋ'];
  t[0x1a] = ['ka', 'ka', 'ka'];
  t[0x1b] = ['kha', 'kha', 'kʰa'];
  t[0x1c] = ['ga', 'ga', 'ɡa'];
  t[0x1d] = ['gha', 'gha', 'ɡʱa'];
  t[0x1e] = ['ŋa', 'ṅa', 'ŋa'];
  t[0x1f] = ['ŋga', 'ṅga', 'ŋɡa'];   // prenasalized — unique to Sinhala
  t[0x20] = ['cha', 'ca', 'tʃa'];
  t[0x21] = ['Cha', 'cha', 'tʃʰa'];
  t[0x22] = ['ja', 'ja', 'dʒa'];
  t[0x23] = ['jha', 'jha', 'dʒʱa'];
  t[0x24] = ['ɲa', 'ña', 'ɲa'];
  t[0x25] = ['jna', 'ña', 'ɲa'];
  t[0x26] = ['ɲja', 'ñja', 'ɲdʒa'];  // prenasalized — unique to Sinhala
  t[0x27] = ['Ta', 'ṭa', 'ʈa'];
  t[0x28] = ['Tha', 'ṭha', 'ʈʰa'];
  t[0x29] = ['Da', 'ḍa', 'ɖa'];
  t[0x2a] = ['Dha', 'ḍha', 'ɖʱa'];
  t[0x2b] = ['Na', 'ṇa', 'ɳa'];
  t[0x2c] = ['NDa', 'ṇḍa', 'ɳɖa'];  // prenasalized — unique to Sinhala
  t[0x2d] = ['ta', 'ta', 'ta'];
  t[0x2e] = ['tha', 'tha', 'tʰa'];
  t[0x2f] = ['da', 'da', 'da'];
  t[0x30] = ['dha', 'dha', 'dʱa'];
  t[0x31] = ['na', 'na', 'na'];
  t[0x33] = ['nda', 'nda', 'nda'];    // prenasalized — unique to Sinhala
  t[0x34] = ['pa', 'pa', 'pa'];
  t[0x35] = ['pha', 'pha', 'pʰa'];
  t[0x36] = ['ba', 'ba', 'ba'];
  t[0x37] = ['bha', 'bha', 'bʱa'];
  t[0x38] = ['ma', 'ma', 'ma'];
  t[0x39] = ['mba', 'mba', 'mba'];    // prenasalized — unique to Sinhala
  t[0x3a] = ['ya', 'ya', 'ja'];
  t[0x3b] = ['ra', 'ra', 'ra'];
  t[0x3d] = ['la', 'la', 'la'];
  t[0x40] = ['va', 'va', 'ʋa'];
  t[0x41] = ['sha', 'śa', 'ʃa'];
  t[0x42] = ['Sha', 'ṣa', 'ʃa'];     // merged with ශ /ʃ/ in modern Sinhala
  t[0x43] = ['sa', 'sa', 'sa'];
  t[0x44] = ['ha', 'ha', 'ɦa'];
  t[0x45] = ['La', 'ḷa', 'ɭa'];
  t[0x46] = ['fa', 'fa', 'fa'];
  t[0x4a] = ['', '', ''];             // virama (hal kirima) — suppresses inherent vowel
  t[0x4f] = ['A', 'ā', 'aː'];
  t[0x50] = ['ae', 'æ', 'æ'];
  t[0x51] = ['aae', 'ǣ', 'æː'];
  t[0x52] = ['i', 'i', 'i'];
  t[0x53] = ['I', 'ī', 'iː'];
  t[0x54] = ['u', 'u', 'u'];
  t[0x56] = ['U', 'ū', 'uː'];
  t[0x58] = ['ri', 'ṛ', 'ri'];
  t[0x59] = ['e', 'e', 'e'];
  t[0x5a] = ['E', 'ē', 'eː'];
  t[0x5b] = ['ai', 'ai', 'aj'];
  t[0x5c] = ['o', 'o', 'o'];
  t[0x5d] = ['O', 'ō', 'oː'];
  t[0x5e] = ['au', 'au', 'aʋ'];
  t[0x5f] = ['li', 'ḷ', 'li'];
  t[0x66] = ['0', '0', '0'];
  t[0x67] = ['1', '1', '1'];
  t[0x68] = ['2', '2', '2'];
  t[0x69] = ['3', '3', '3'];
  t[0x6a] = ['4', '4', '4'];
  t[0x6b] = ['5', '5', '5'];
  t[0x6c] = ['6', '6', '6'];
  t[0x6d] = ['7', '7', '7'];
  t[0x6e] = ['8', '8', '8'];
  t[0x6f] = ['9', '9', '9'];
  t[0x72] = ['ri', 'ṛ', 'ri'];
  t[0x73] = ['ri', 'ṝ', 'riː'];
  t[0x74] = ['. ', '. ', '. '];

  return t;
})();
